### ISSUE TITLE
Guidance on running revapi in a github action - seems to pass when fails locally

### ISSUE THREAD

**Issue by kbendick** [palantir/gradle-revapi#551]
## What happened?

`./gradlew revapi` is passing during [our github action](https://github.com/apache/iceberg/blob/ec1beb99ac4cfc50c588d8af237363a961cc12ea/.github/workflows/api-binary-compatibility.yml#L49) in the Apache Iceberg project when breaking changes are introduced.

These same breaking changes cause failures locally.

I've seen it mostly say `skipping`. I believe this is because we have the github `cache` action.

I removed the [github `cache` action in my fork](https://github.com/kbendick/iceberg/blob/e3b540ed3e4a046f9c4f73ecabdd37d4b7be1083/.github/workflows/api-binary-compatibility.yml#L44). That seems to cause `revapi` to run (revapiAnalyze running is in the debug output), but it still passes.

Our `.palantir/revapi.yml` file can be found here: https://github.com/apache/iceberg/blob/master/.palantir/revapi.yml

## What did you want to happen?

For a breaking change in a branch with `master` as its target to break in our Github Action CI, like it does locally.

Here's an example that _should_ fail (or at least does locally):
- https://github.com/kbendick/iceberg/runs/6761402278?check_suite_focus=true
- https://github.com/kbendick/iceberg/pulls

Is it possible that when we `git checkout` via `actions/checkout`, that the proper branch and overrride is not discovered? Are there CLI flags I can use to force it to use a specific version JAR from maven as the old version?

Thank you for developing this gradle plugin. We'd love to get this resolved as the Apache Iceberg community has come to rely on this and we need it to work in our CI as well (and will make the necessary changes, but need help determining what they are). Thank you!

**Comment by kbendick** [comment]
I resolved this issue.

The problem is that we were using the github `checkout` action with the default checkout depth of 1, which doesn't checkout tags etc.

Setting the checkout depth to 0 (fetch all tags) resolves the problem as then `git describe` works as expected.

For reference for anybody else, here's what we used:
```
      - uses: actions/checkout@v3
        with:
          # fetch-depth of zero ensures that the tags are pulled in and we're not in a detached HEAD state
          # revapi depends on the tags, specifically the tag from git describe, to find the relevant override
          # in the .palantir/revapi.yml file
          #
          # See https://github.com/actions/checkout/issues/124
          fetch-depth: 0
```

See https://github.com/apache/iceberg/pull/4989
