### ISSUE TITLE
RevApi requires up to date with develop

### ISSUE THREAD

**Issue by felixdesouza** [palantir/gradle-revapi#77]
## What happened?

I made some internal code breaks. I resolved the breaks, but this was against an "old" tag i.e. someone released just after I resolved the breaks, so when this merged, I got a semantic merge conflict where I needed to resolve the breaks again and the metadata for the previous tag was ignored.

i.e. develop is compared to 0.162.0 vs 0.161.1 (where I resolved the breaks). 

## What did you want to happen?

It should recognise the break when it happened vs when it merged into develop, and not require me to be up to date with develop or submit extra prs after develop breaks.

## What could we do?

Thoughts are whether we keyed the file by the break instead of the version, and the key can be some sort of hash. This would avoid the case outlined above, as you'd just look up the hash of the break. We *could* keep the version, but as some metadata, and that would give you the "logical" time when this break was made vs when it merged into develop. But it would be purely for informational purposes, unless there was another use for the version?

e.g. from
```yml
acceptedBreaks:
  0.162.2:
    com.palantir.atlasdb:atlasdb-config:
    - code: "java.method.removed"
      old: "method com.palantir.atlasdb.factory.ImmutableLocalPaxosServices.Builder\
        \ com.palantir.atlasdb.factory.ImmutableLocalPaxosServices.Builder::pingableLeader(com.palantir.leader.PingableLeader)"
      new: null
      justification: "this is internal code"
```

to

```yml
acceptedBreaks:
  com.palantir.atlasdb:atlasdb-config:
    0fb0236503:
      - code: "java.method.removed"
        old: "method com.palantir.atlasdb.factory.ImmutableLocalPaxosServices.Builder"
        new: null
        justification: "this is internal code"
        version-introduced: 0.162.2
      # any other hash collisions
```

@iamdanfox, @CRogers for SA.
